#!/bin/bash

POSIXLY_CORRECT=yes
i=0
repeat=0
datetime='([1-9][0-9][0-9][0-9])-([0-9][0-2])-([0-9][0-9]) ([0-2][0-9]):([0-6][0-9]):([0-6][0-9])'
integer='^[0-9]+$'

while getopts ":t: :a: :b: :w: h" opt; do
	case ${opt} in
		h )
			echo "napoveda"
			exit 0
			;;
  	a )
  		datetime_after=$OPTARG
  		if ! [[ $datetime_after =~ $datetime ]]; then
				echo "Error: datetime must be in format YYYY-MM-DD HH:MM:SS"
				exit 1
			fi
  	  ;;
  	b )
  		datetime_before=$OPTARG
  		if ! [[ $datetime_before =~ $datetime ]]; then
				echo "Error: datetime must be in format YYYY-MM-DD HH:MM:SS"
				exit 1
			fi
  	  ;;
	  t )
  		tickers[i]=$OPTARG
  	  ;;	
  	w )
  		if [[ $repeat == 1 ]]; then
  			echo "Error: repeated option -w"
  			exit 1
  		fi
  		width=$OPTARG
  		if ! [[ $width =~ $integer ]]; then
  			echo "Error: width must be an integer grater than 0"
  		fi
  		repeat=1
  	  ;;
  	\? )
  		echo "Error: invalid option -$OPTARG" 1>&2
  		exit 1
  	  ;;
  	: )
  		echo "Error: invalid option -$OPTARG requires argument" 1>&2
  		exit 1
  	  ;;
	  esac
	  i=$i+1
done
shift $((OPTIND -1))

#echo ${tickers[@]}


echo "$ticker"

